# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
        Install-Script -Name winget-install -Force
        winget-install.ps1
    displayName: 'Install winget'
  
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       Invoke-WebRequest -Method 'POST' -Uri 'http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8a26c76e-5a63-42d5-9f7d-df053c273363?P1=1675811184&P2=404&P3=2&P4=VYStpoSOdHl1xRtxf1E5CCniL7fsKuakHY12ECkg%2bYwpU%2ffZe3XM6jfDJctyjA3zUwprE7y1RRTrOOHmzBOfUw%3d%3d' -ContentType 'application/x-www-form-urlencoded' -UseBasicParsing
  #       get-appxpackage -Name Microsoft.MicrosoftOfficeHub
  #   displayName: 'Install Microsoft 365'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Invoke-WebRequest -Method 'POST' -Uri 'http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8a26c76e-5a63-42d5-9f7d-df053c273363?P1=1675811184&P2=404&P3=2&P4=VYStpoSOdHl1xRtxf1E5CCniL7fsKuakHY12ECkg%2bYwpU%2ffZe3XM6jfDJctyjA3zUwprE7y1RRTrOOHmzBOfUw%3d%3d' -ContentType 'application/x-www-form-urlencoded' -UseBasicParsing
        # get-appxpackage -Name Microsoft.MicrosoftOfficeHub
        winget install 9WZDNCRD29V9
    displayName: 'Install Microsoft 365'
    
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # - script: |
  #     npm install -g pnpm
  #     pnpm install
  #   displayName: 'pnpm install'

  - script: |
      npm run vp-test
    displayName: 'pnpm vp-test'
